In [13]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import pandas as pd
import cv2
import os
import glob
import time
import shutil
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

In [15]:
from LeNet5 import FC,Conv2D
from Datapreprocessing import Data

In [1]:
from Datapreprocessing import Data
Data = Data()

In [2]:
Data.dataset_split('train')

train_images: (63322, 256, 256, 3)
<class 'numpy.ndarray'>
train_labels: 63322
<class 'numpy.ndarray'>
花了 593 s


(array([[[[175, 171, 152],
          [175, 171, 152],
          [173, 169, 150],
          ...,
          [162, 165, 156],
          [163, 166, 157],
          [162, 165, 156]],
 
         [[169, 165, 146],
          [170, 166, 147],
          [170, 166, 147],
          ...,
          [128, 134, 123],
          [119, 125, 114],
          [112, 118, 107]],
 
         [[161, 157, 138],
          [162, 158, 139],
          [167, 163, 144],
          ...,
          [ 89,  97,  86],
          [ 87,  95,  84],
          [ 87,  95,  84]],
 
         ...,
 
         [[157, 150, 131],
          [155, 148, 129],
          [158, 151, 132],
          ...,
          [130, 124, 105],
          [130, 124, 105],
          [129, 123, 104]],
 
         [[159, 152, 133],
          [158, 151, 132],
          [161, 154, 135],
          ...,
          [130, 124, 105],
          [130, 124, 105],
          [129, 123, 104]],
 
         [[161, 154, 135],
          [160, 153, 134],
          [163, 156, 137],
   

In [3]:
Data.dataset_split('validation')

validation_images: (450, 256, 256, 3)
<class 'numpy.ndarray'>
validation_labels: 450
<class 'numpy.ndarray'>
花了 0 s


(array([[[[173, 173, 167],
          [177, 177, 171],
          [180, 180, 174],
          ...,
          [227, 227, 227],
          [227, 227, 227],
          [227, 227, 227]],
 
         [[199, 198, 194],
          [206, 205, 201],
          [214, 213, 209],
          ...,
          [225, 225, 225],
          [225, 225, 225],
          [225, 225, 225]],
 
         [[235, 234, 232],
          [240, 239, 236],
          [246, 244, 242],
          ...,
          [224, 224, 224],
          [224, 224, 224],
          [224, 224, 224]],
 
         ...,
 
         [[152, 158, 159],
          [147, 153, 155],
          [144, 150, 151],
          ...,
          [ 22,  25,  24],
          [ 22,  25,  24],
          [ 23,  26,  25]],
 
         [[145, 151, 156],
          [142, 148, 153],
          [137, 143, 148],
          ...,
          [ 20,  25,  22],
          [ 24,  29,  25],
          [ 30,  35,  31]],
 
         [[157, 166, 170],
          [159, 168, 172],
          [155, 164, 168],
   

In [4]:
Data.dataset_split('test')

test_images: (450, 256, 256, 3)
<class 'numpy.ndarray'>
test_labels: 450
<class 'numpy.ndarray'>
花了 1 s


(array([[[[ 97, 231, 185],
          [ 95, 229, 183],
          [ 94, 228, 182],
          ...,
          [ 72, 216, 163],
          [ 73, 217, 164],
          [ 71, 219, 165]],
 
         [[ 97, 231, 185],
          [ 95, 229, 183],
          [ 95, 229, 183],
          ...,
          [ 72, 216, 163],
          [ 72, 216, 163],
          [ 70, 218, 164]],
 
         [[ 97, 231, 185],
          [ 96, 230, 184],
          [ 95, 229, 183],
          ...,
          [ 71, 215, 162],
          [ 70, 215, 162],
          [ 68, 216, 162]],
 
         ...,
 
         [[ 21,  65,  88],
          [ 23,  71,  93],
          [ 12,  63,  86],
          ...,
          [ 65, 213, 165],
          [ 67, 219, 171],
          [ 65, 221, 180]],
 
         [[ 24,  73,  95],
          [ 27,  77,  99],
          [ 15,  70,  92],
          ...,
          [ 62, 210, 160],
          [ 65, 219, 169],
          [ 67, 225, 184]],
 
         [[ 23,  73,  95],
          [ 30,  81, 104],
          [ 22,  80, 102],
   

In [ ]:
class FC:
    def __init__(self, input_size, output_size):
        self.weights = np.random.randn(input_size, output_size) * 0.01  # 初始化权重
        self.biases = np.zeros((1, output_size))  # 初始化偏置

    def forward(self, inputs):
        self.inputs = inputs
        self.outputs = np.dot(self.inputs, self.weights) + self.biases
        return self.outputs

    def backward(self, d_outputs, learning_rate):
        d_weights = np.dot(self.inputs.T, d_outputs)
        d_biases = np.sum(d_outputs, axis=0, keepdims=True)
        d_inputs = np.dot(d_outputs, self.weights.T)

        # 更新参数
        self.weights -= learning_rate * d_weights
        self.biases -= learning_rate * d_biases

        return d_inputs