In [79]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import glob
import time
import shutil
import pickle
import random
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

In [80]:
from Assignment2 import LeNet5, TwoLayerNet
import Assignment2 as A2
from Datapreprocessing import Data
model = LeNet5()
Data = Data()

In [81]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import cv2
import os
import glob
import time
import shutil
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"





class Data:
    def __init__(self):
        return

    def file_split(self, file):
        os.mkdir(file) # 創建資料夾
        imagelist = os.listdir('C:/Users/User/Desktop/Deep Learning/Assignment-1 Image classiication/images')
        f = open(file + '.txt') # 打開train.txt檔

        for i in range(22, 50):
            os.mkdir(file + '/' + file + str(i)) # 創建50個類別的資料夾

            for txt in f.readlines(): #逐行讀取test.txt

                for image in glob.glob('images/' + imagelist[i] + '/*.*'): # 讀取images下所有檔案

                    if (txt[17:32] == image[17:32]): # 對比txt及image名稱一不一樣

                        if '.JPEG ' in txt[17:34]: # 1位數
                            shutil.copy('images/' + imagelist[i] + '/' + image[17:28] +'.JPEG', './' + file + '/'+ file + str(i))
                        elif '.JPEG' in txt[17:34]: # 2位數
                            shutil.copy('images/' + imagelist[i] + '/' + image[17:29] +'.JPEG', './' + file + '/'+ file + str(i)) # 複製檔案至test目錄
                        elif '.JPE' in txt[17:34]: # 3位數
                            shutil.copy('images/' + imagelist[i] + '/' + image[17:30] +'.JPEG', './' + file + '/'+ file + str(i))
                        elif '.JP' in txt[17:34]: # 4位數
                            shutil.copy('images/' + imagelist[i] + '/' + image[17:31] +'.JPEG', './' + file + '/'+ file + str(i))
                        elif '.J' in txt[17:34]: # 5位數
                            shutil.copy('images/' + imagelist[i] + '/' + image[17:32] +'.JPEG', './' + file + '/'+ file + str(i))

        f.seek(0)


    def dataset_split(self, file):
        if file == 'train':
            global  train_labels, train_images
            starttime = int(time.time())
            train_images = []
            image_list = os.listdir('train/')
            image_list.sort(key = lambda x: int(x[5:]))


            for i in range(len(image_list)):
                j = 0
                for images in glob.glob('train/' + image_list[i] + '/*'):
                    j+=1
                    if j == 121: # 只取前120張
                        break
                    img = cv2.imread(images) # 圖片讀檔
#                     img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # 轉灰階
                    img = cv2.resize(img, (256, 256))
                    train_images.append(img)

            train_images = np.array(train_images)



            train_labels = []
            image_list = os.listdir('train/')
            image_list.sort(key = lambda x: int(x[5:]))

            for i in range(len(image_list)):
                j = 0
                for labels in glob.glob('train/' + image_list[i] + '/*'):
                    j+=1
                    if j == 121:
                        break
                    train_labels.append(i)
            train_labels = np.array(train_labels)

            endtime = int(time.time()) # 計時結束
            print("train_images:",train_images.shape)
            print(type(train_images))
            print("train_labels:",len(train_labels))
            print(type(train_labels))
            print('花了',endtime-starttime,'s')

            return train_images, train_labels

        elif file == 'validation':
            global validation_labels, validation_images
            starttime = int(time.time()) # 計時開始
            validation_images = []
            image_list = os.listdir('validation/')
            image_list.sort(key = lambda x: int(x[10:]))

            for i in range(len(image_list)):
                for images in glob.glob('validation/' + image_list[i] + '/*'):
                    img = cv2.imread(images) # 圖片讀檔
#                     img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # 轉灰階
                    img = cv2.resize(img, (256, 256))
                    validation_images.append(img)

            validation_images = np.array(validation_images)



            validation_labels = []
            image_list = os.listdir('validation/')
            image_list.sort(key = lambda x: int(x[10:]))


            for i in range(len(image_list)):
                for labels in glob.glob('validation/' + image_list[i] + '/*'):
                    validation_labels.append(i)

            validation_labels = np.array(validation_labels)

            endtime = int(time.time()) # 計時結束
            print("validation_images:",validation_images.shape)
            print(type(validation_images))
            print("validation_labels:",len(validation_labels))
            print(type(validation_labels))
            print('花了',endtime-starttime,'s')

            return validation_images, validation_labels

        elif file == 'test':
            global test_labels, test_images
            starttime = int(time.time())
            # images
            test_images = []
            image_list = os.listdir('test/')
            image_list.sort(key = lambda x: int(x[4:]))

            for i in range(len(image_list)):
                for images in glob.glob('test/' + image_list[i] + '/*'):
                    img = cv2.imread(images) # 圖片讀檔
#                     img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # 轉灰階
                    img = cv2.resize(img, (256, 256))
                    test_images.append(img)

            test_images = np.array(test_images)

            # labels
            test_labels = []
            image_list = os.listdir('test/')
            image_list.sort(key = lambda x: int(x[4:]))


            for i in range(len(image_list)):
                for labels in glob.glob('test/' + image_list[i] + '/*'):
                    test_labels.append(i)

            test_labels = np.array(test_labels)
            endtime = int(time.time())

            print("test_images:",test_images.shape)
            print(type(test_images))
            print("test_labels:",len(test_labels))
            print(type(test_labels))
            print('花了',endtime-starttime,'s')

            return test_images, test_labels


In [82]:
Data().dataset_split(file = 'train')

train_images: (6000, 256, 256, 3)
<class 'numpy.ndarray'>
train_labels: 6000
<class 'numpy.ndarray'>
花了 8 s


(array([[[[175, 171, 152],
          [175, 171, 152],
          [173, 169, 150],
          ...,
          [162, 165, 156],
          [163, 166, 157],
          [162, 165, 156]],
 
         [[169, 165, 146],
          [170, 166, 147],
          [170, 166, 147],
          ...,
          [128, 134, 123],
          [120, 124, 114],
          [113, 117, 108]],
 
         [[161, 157, 138],
          [162, 158, 139],
          [167, 163, 144],
          ...,
          [ 89,  98,  85],
          [ 88,  95,  84],
          [ 89,  95,  84]],
 
         ...,
 
         [[157, 150, 131],
          [155, 148, 129],
          [158, 151, 132],
          ...,
          [131, 124, 105],
          [131, 124, 105],
          [130, 123, 104]],
 
         [[159, 152, 133],
          [158, 151, 132],
          [161, 154, 135],
          ...,
          [130, 124, 105],
          [130, 124, 105],
          [129, 123, 104]],
 
         [[161, 154, 135],
          [160, 153, 134],
          [163, 156, 137],
   

In [83]:
Data().dataset_split('validation')

validation_images: (450, 256, 256, 3)
<class 'numpy.ndarray'>
validation_labels: 450
<class 'numpy.ndarray'>
花了 1 s


(array([[[[173, 173, 167],
          [177, 177, 171],
          [180, 180, 174],
          ...,
          [227, 227, 227],
          [227, 227, 227],
          [227, 227, 227]],
 
         [[199, 199, 194],
          [206, 205, 200],
          [214, 213, 208],
          ...,
          [225, 225, 225],
          [225, 225, 225],
          [225, 225, 225]],
 
         [[235, 234, 230],
          [240, 239, 235],
          [246, 245, 241],
          ...,
          [224, 224, 224],
          [224, 224, 224],
          [224, 224, 224]],
 
         ...,
 
         [[153, 157, 161],
          [147, 153, 155],
          [145, 149, 153],
          ...,
          [ 22,  25,  23],
          [ 23,  25,  24],
          [ 23,  26,  24]],
 
         [[146, 151, 156],
          [141, 149, 153],
          [138, 143, 148],
          ...,
          [ 19,  25,  22],
          [ 25,  29,  25],
          [ 30,  35,  31]],
 
         [[157, 166, 170],
          [159, 168, 172],
          [155, 164, 168],
   

In [84]:
Data().dataset_split('test')

test_images: (450, 256, 256, 3)
<class 'numpy.ndarray'>
test_labels: 450
<class 'numpy.ndarray'>
花了 0 s


(array([[[[ 97, 231, 185],
          [ 95, 229, 183],
          [ 94, 228, 182],
          ...,
          [ 72, 216, 163],
          [ 72, 218, 164],
          [ 72, 219, 165]],
 
         [[ 97, 231, 185],
          [ 95, 229, 183],
          [ 95, 229, 183],
          ...,
          [ 72, 216, 163],
          [ 71, 217, 163],
          [ 71, 218, 164]],
 
         [[ 97, 231, 185],
          [ 96, 230, 184],
          [ 95, 229, 183],
          ...,
          [ 71, 215, 162],
          [ 70, 216, 162],
          [ 69, 216, 162]],
 
         ...,
 
         [[ 21,  65,  88],
          [ 24,  71,  93],
          [ 12,  63,  86],
          ...,
          [ 65, 213, 165],
          [ 67, 219, 173],
          [ 66, 222, 180]],
 
         [[ 25,  73,  95],
          [ 27,  77,  99],
          [ 15,  70,  92],
          ...,
          [ 62, 210, 161],
          [ 65, 218, 170],
          [ 68, 226, 181]],
 
         [[ 24,  73,  95],
          [ 30,  81, 104],
          [ 23,  80, 102],
   

In [55]:
train_images = train_images - np.mean(train_images)

In [57]:
train_images.shape

(6000, 256, 256, 3)

In [85]:
batch_size = 64
model1 = TwoLayerNet(batch_size, 256*256*3, 1200, 50)
D_out = 50

In [87]:
losses = []
#optim = optimizer.SGD(model.get_params(), lr=0.0001, reg=0)
optim = A2.SGDMomentum(model1.get_params(), lr=0.0001, momentum=0.80, reg=0.00003)
criterion = A2.CrossEntropyLoss()

# TRAIN
ITER = 25000
for i in range(ITER):
	# get batch, make onehot
	X_batch, Y_batch = A2.get_batch(train_images, train_labels, batch_size)
	Y_batch = A2.MakeOneHot(Y_batch, D_out)

	# forward, loss, backward, step
	Y_pred = model1.forward(X_batch)
	loss, backout = criterion.get(Y_pred, Y_batch)
	model.backward(backout)
	optim.step()

	if i % 100 == 0:
		print("%s%% iter: %s, loss: %s" % (100*i/ITER,i, loss))
		losses.append(loss)


# save params
weights = model.get_params()
with open("weights.pkl","wb") as f:
	pickle.dump(weights, f)

A2.draw_losses(losses)



# TRAIN SET ACC
Y_pred = model1.forward(train_images)
result = np.argmax(Y_pred, axis=1) - train_labels
result = list(result)
print("TRAIN--> Correct: " + str(result.count(0)) + " out of " + str(train_images.shape[0]) + ", acc=" + str(result.count(0)/train_images.shape[0]))

# TEST SET ACC
Y_pred = model1.forward(test_images)
result = np.argmax(Y_pred, axis=1) - test_labels
result = list(result)
print("TEST--> Correct: " + str(result.count(0)) + " out of " + str(test_images.shape[0]) + ", acc=" + str(result.count(0)/test_images.shape[0]))

ValueError: shapes (64,256,256,3) and (196608,1200) not aligned: 3 (dim 3) != 196608 (dim 0)

In [76]:
S = X_batch.shape[0]
S

64

In [72]:
X_new = X_batch.reshape(S, -1)
X_new

array([[ -11.54863617,  -12.54863617,  -16.54863617, ...,    6.45136383,
          13.45136383,    6.45136383],
       [-111.54863617, -110.54863617, -110.54863617, ..., -111.54863617,
        -111.54863617, -111.54863617],
       [ -99.54863617,  -83.54863617,  -76.54863617, ...,  -30.54863617,
         -25.54863617,  -20.54863617],
       ...,
       [ -76.54863617,   -5.54863617,  -31.54863617, ...,  -92.54863617,
          -0.54863617,  -29.54863617],
       [  -0.54863617,   39.45136383,   44.45136383, ...,   87.45136383,
         101.45136383,  113.45136383],
       [  34.45136383,   46.45136383,   50.45136383, ...,  123.45136383,
         122.45136383,  124.45136383]])

In [73]:
256*256*3

196608