In [8]:
H = 256
W = 256
C = 3
FH = 4
FW = 4

x_col = np.zeros((C * FH * FW, H * W))
x_col.shape

(48, 65536)

In [9]:
w_row = w.reshape(F, C * FH * FW)
w_row

NameError: name 'w' is not defined

In [20]:
180000*12

2160000

In [3]:
np.log(3)

1.0986122886681098

In [4]:
import numpy as np
Y = np.zeros((300, 6, 28, 28))
print(Y)

[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   

In [6]:
Y[0,0,0,0]

0.0

In [7]:
Y.ndim

4

In [6]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
import numpy as np
a = np.array(a)
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.rot90(a)

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [9]:
a = 256-4
a1 = a / 4
a2 = a1-4
a3 = a2/4
a4 = a3-4
a5 = a4/4

In [10]:
a5

2.6875

In [14]:
252/3

84.0

In [15]:
784**.5

28.0